### ISSUE TITLE
Unmaintained yaml-rust dependency, should use forked version instead

### ISSUE THREAD

**Issue by mtnking** [rust-cli/config-rs#574] opened 2024-07-31 15:27 UTC
Crate:     yaml-rust
Version:   0.4.5
Warning:   unmaintained
Title:     yaml-rust is unmaintained.
Date:      2024-03-20
ID:        RUSTSEC-2024-0320
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0320

Please consider switching to the actively maintained yaml-rust2 fork of the original project:

    [yaml-rust2](https://github.com/Ethiraric/yaml-rust2)
    [yaml-rust2 @ crates.io](https://crates.io/crates/yaml-rust2)

**Comment by AdamLeyshon** [comment] 2024-08-02 15:08
Duplicate of https://github.com/mehcode/config-rs/issues/563

**Closed** 2024-10-23 09:51 UTC
