### ISSUE TITLE
bug: config `0.14.0` only supports lowercase fields (regression since `0.13.4`)

### ISSUE THREAD

**Issue by vladgon** [rust-cli/config-rs#531] opened 2024-02-03 00:45 UTC
Failed to deserialize camelcase fields for yaml file
https://github.com/vladgon/rust/blob/49854f6c3d02bf7ae4a8d123ac9ecfbbe3959a56/wspace/wg_util/src/common/config/model.rs#L24
```rust
#[derive(Deserialize, Serialize, Debug)]
#[allow(non_snake_case)]
pub struct Kafka {
    pub broker: String,
    pub topic: String,
    pub pollSleep: u64,  //<---
}
```

https://github.com/vladgon/rust/blob/49854f6c3d02bf7ae4a8d123ac9ecfbbe3959a56/wspace/wg_sample_app/resources/app_config.yaml#L9
```yaml
kafka:
  broker: localhost:29092
  topic: rust
  pollSleep: 1000
```

https://github.com/vladgon/rust/blob/49854f6c3d02bf7ae4a8d123ac9ecfbbe3959a56/wspace/wg_util/src/common/config/app_config.rs#L73-L78

**Comment by polarathene** [comment] 2024-02-03 02:51
Probably have to compare the crate version differences of dependencies? Unless it was an actual internal change introduced to `config-rs` (_I recall some work was contributed to rework deserializing_).

Is this specific to YAML only? Could you try it with a different config file type?

---

If it's specific to YAML, there is plans to change the crate used: https://github.com/mehcode/config-rs/pull/474

I'm hoping to have time next week to tackle that and related PRs.

**Comment by vladgon** [comment] 2024-02-03 17:22
Tested with toml file same issue, works with 0.13.4, fails with 0.14.0

```console
Setting Tracing filter config wg_util=debug,server=debug
2024-02-03T17:19:42.381705Z DEBUG ThreadId(01) wg_util::common::config::rust_app: 29: Using config files: "/Users/vova/workspace/rust/wspace/wg_sample_app/resources/app_config.toml"    
thread 'main' panicked at wg_util/src/common/config/app_config.rs:77:82:
missing field `pollSleep`
stack backtrace:
```

**Comment by polarathene** [comment] 2024-02-03 21:12
> works with 0.13.4, fails with 0.14.0

Ok, awesome!

So now we know that it's not format specific, it's either due to a dependency update or something that changed in the actual `config-rs` code. That's a tricky one someone will need to invest time into to track down.

There is a [211 commit difference](https://github.com/mehcode/config-rs/compare/v0.13.4...0.14.0) to wade through, although it's not that bad as I recall this project uses merge commits from PRs rather than squash, so the actual range should be less.

I am aware of an approach called a git bisect that performs builds on different commits until it finds the one where the breakage was introduced. I've not used this before and assume it'll know to only test against the merge commits in that range rather than partial series of commits from a PR. It'd do something like start halfway through that list and if it works properly, then tries the halfway point in that smaller range and so forth.

Alternatively you could look through the commit history manually and see if anything stands out.

---

At a guess if it's failing with the rename, it may fail at other serde attributes that worked previously, which should help narrow it down to commit range between releases for specific files instead 👍 

In fact at a glance it could be this: https://github.com/mehcode/config-rs/pull/354

I assume that'd mean your field is already internally treated as `pollsleep`, hence the breakage.

The project also documents the change history [with a changelog](https://github.com/mehcode/config-rs/blob/master/CHANGELOG.md#0140---2024-02-01) thanks to @matthiasbeyer , that should help a little due to the merge approach. Give that a look, there's some other changes that could have been the culprit doing similar transforms.

---

Once that's pinned down, then we'd need to assess the intended fix vs the breakage it introduced and if both can remain fixed or if one has to be preferred 🤷‍♂️ 

Either way, sounds like a new test case for the project 😅

**Comment by polarathene** [comment] 2024-02-03 21:15
I updated the title, it's still based on an assumption but may be more descriptive of what the actual regression is.

**Comment by vladgon** [comment] 2024-02-03 23:09
I think you should have a unit test for this case, just wanted to let you know about the issue.

--Vladimir

**Comment by jpmckinney** [comment] 2024-02-09 00:00
Yes, I think #354 is the cause. I would also like to be able to read in keys that don't get lowercased.

**Comment by max-m** [comment] 2024-03-06 20:32
I noticed this change the hard way as well, my service exploded because case sensitive keys were suddenly converted to lower case.
Part of my parsed config is a hash map with case sensitive keys that must be passed as is to a downstream service.
```rust
struct Settings {
  ...
  downstream_config: HashMap<String, serde_json::Value>,
  ...
}
```
With version 0.14.0 all the keys of that map are now lowercase.
As a workaround I’ve rolled back to 0.13.4 for now.

And now that I think about it, I suppose this was also the issue I had when I tried to add a struct to my config that had `#[serde(rename_all = "camelCase")]` set and it couldn’t deserialize the config because `myKey` was apparently not set, even though it was. :thinking:

**Comment by HactarCE** [comment] 2024-11-15 02:24
I also just spent an hour or two debugging this in [Hyperspeedcube](https://github.com/HactarCE/Hyperspeedcube/)

**Comment by primeos-work** [comment] 2024-11-15 14:16
Any ideas how to best proceed here or rather how to make a decision whether this library should be case-sensitive (as it was up to version 0.13.4) or case-insensitive (as it is since version 0.14.0, where all keys are converted to lowercase)? (Voting might be nice but difficult - ultimately it's up to the maintainers though - cc @epage and @alerque in case you have some spare time to move this forward / make a decision; there's already https://github.com/rust-cli/config-rs/pull/543 btw which was close to being merged)

Basically this isn't a bug but a somewhat under documented "feature" (at least in the changelog!). The [changelog for version 0.14.0](https://github.com/rust-cli/config-rs/blob/main/CHANGELOG.md#0140---2024-02-01) doesn't really mention this major breaking change ("https://github.com/mehcode/config-rs/pull/354 Fix uppercase lowercase issues" is quite subtle...) but the README now clearly states that this library is "Is case insensitive and all the keys are converted to lowercase internally".

AFAIK/IIRC the change to lowercase (#354) was only intended to fix issues with environment variables (#340). The problem was that environment variable names are converted to lowercase internally and so it was not possible to override configuration keys that contain uppercase characters via env vars. Instead of making env vars case-senstive, it was decided to make config-rs case-insnsitive by always lowercasing all configuration keys (https://github.com/rust-cli/config-rs/pull/354#issuecomment-1171120245). This fixed #340 but caused major regressions for downstream since many projects depended on the case-sensitivity.

One internal regression seems to be that Serde renamed fields are no longer supported: https://github.com/rust-cli/config-rs/issues/522.

Looking at the links in this issue, some users of this library have downgraded to version 0.13.4:
- https://github.com/science-computing/butido/pull/353
- https://github.com/rust-cli/config-rs/issues/531#issuecomment-1981733959
- https://github.com/lapce/lapce/commit/80ccc709dff6b94ad9b40d2981bd7f6a38c5d3e3
- https://github.com/TheContrappostoShop/Odyssey/pull/18
- https://github.com/siryancealot-enterprises/rust-react-app-hello-world/commit/d8067ee2667d966aad41e54e98ecb6b541a67d8c
- https://github.com/HactarCE/Hyperspeedcube/commit/306e4f546defb7cc7ab737b9388408e4eac94c81

One project switched to another library:
- https://github.com/Ionizing/rsgrad/issues/11

And one PR has been blocked by this change:
- https://github.com/martinvonz/jj/pull/3023#discussion_r1490324596

**Comment by alerque** [comment] 2024-11-15 15:31
As mentioned before the migration, I'd still be willing to jump in a bit here and there to facilitate, but I haven't been granted any permissions on this since the migration.

**Comment by epage** [comment] 2024-11-15 22:32
> but I haven't been granted any permissions on this since the migration.

what permissions would be needed to do such a thing?

**Comment by epage** [comment] 2024-11-15 22:37
> Any ideas how to best proceed here or rather how to make a decision whether this library should be case-sensitive (as it was up to version 0.13.4) or case-insensitive (as it is since version 0.14.0, where all keys are converted to lowercase)? (Voting might be nice but difficult - ultimately it's up to the maintainers though 

imo we should be case sensitive by default for config files.  If we were to support case insensitivity, that should be an opt-in feature somehow (generics?).  However, the core problem is dealing with env variables which, on Windows, are case insensitive which we should match.

My questions
- What would a solution look like that restricts case insensitivty to only env variables, maybe even only on Windows?
- Is the problem with env variables sufficient to hold up un-breaking everyone else?

**Comment by epage** [comment] 2024-12-13 19:30
btw #609 is another bug related to lower casing that we should keep in mind with any kind of fix.

**Comment by epage** [comment] 2024-12-17 20:21
FYI I've posted a revert at #613

**Closed** 2024-12-17 20:27 UTC
Labels: C-bug, M-breaking-change
